// Generated by gencpp from file robot_msg/omni_perception.msg
// DO NOT EDIT!


#ifndef ROBOT_MSG_MESSAGE_OMNI_PERCEPTION_H
#define ROBOT_MSG_MESSAGE_OMNI_PERCEPTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace robot_msg
{
template <class ContainerAllocator>
struct omni_perception_
{
  typedef omni_perception_<ContainerAllocator> Type;

  omni_perception_()
    : header()
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)
    , id(0)
    , score(0)
    , target_lock(0)  {
    }
  omni_perception_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)
    , id(0)
    , score(0)
    , target_lock(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef int8_t _id_type;
  _id_type id;

   typedef int8_t _score_type;
  _score_type score;

   typedef int8_t _target_lock_type;
  _target_lock_type target_lock;





  typedef boost::shared_ptr< ::robot_msg::omni_perception_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msg::omni_perception_<ContainerAllocator> const> ConstPtr;

}; // struct omni_perception_

typedef ::robot_msg::omni_perception_<std::allocator<void> > omni_perception;

typedef boost::shared_ptr< ::robot_msg::omni_perception > omni_perceptionPtr;
typedef boost::shared_ptr< ::robot_msg::omni_perception const> omni_perceptionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msg::omni_perception_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msg::omni_perception_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msg::omni_perception_<ContainerAllocator1> & lhs, const ::robot_msg::omni_perception_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.yaw == rhs.yaw &&
    lhs.id == rhs.id &&
    lhs.score == rhs.score &&
    lhs.target_lock == rhs.target_lock;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msg::omni_perception_<ContainerAllocator1> & lhs, const ::robot_msg::omni_perception_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msg::omni_perception_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msg::omni_perception_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msg::omni_perception_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msg::omni_perception_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msg::omni_perception_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msg::omni_perception_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msg::omni_perception_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bcf02bf291fe4deb8dd921151076c58f";
  }

  static const char* value(const ::robot_msg::omni_perception_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbcf02bf291fe4debULL;
  static const uint64_t static_value2 = 0x8dd921151076c58fULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msg::omni_perception_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msg/omni_perception";
  }

  static const char* value(const ::robot_msg::omni_perception_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msg::omni_perception_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 yaw\n"
"int8 id\n"
"int8 score\n"
"int8 target_lock\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::robot_msg::omni_perception_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msg::omni_perception_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.yaw);
      stream.next(m.id);
      stream.next(m.score);
      stream.next(m.target_lock);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct omni_perception_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msg::omni_perception_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msg::omni_perception_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.id);
    s << indent << "score: ";
    Printer<int8_t>::stream(s, indent + "  ", v.score);
    s << indent << "target_lock: ";
    Printer<int8_t>::stream(s, indent + "  ", v.target_lock);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSG_MESSAGE_OMNI_PERCEPTION_H
